### ISSUE TITLE
is it possible to remove double slashes? 

### ISSUE THREAD

**Issue by v3nt** [dustinspecker/gulp-modify-css-urls#41]
This seems to happen when the url in css starts with a slash.

Also an issue with ./ paths.

    background-image: url(../images/images/icon-target-red.gif); 
    // https://fancycdn.com/wp-content/themes/wonkhe-roots-master/templates-aux/wonkfest-banners/../images/images/wonkfest-logo-target.gif?cache-buster
    background-image: url(/images/images/icon-target-red.gif);
     //  https://fancycdn.com/wp-content/themes/wonkhe-roots-master/templates-aux/wonkfest-banners//images/images/wonkfest-logo-target.gif?cache-buster

thanks.

**Comment by dustinspecker** [comment]
Hey @v3nt,

Sorry for the long delay in getting back to you. Is this still an issue? If so, it feels like this is a good example of using the `modify` option instead of `prepend`.

**Comment by v3nt** [comment]
@dustinspecker - not sure as its been a while. Think i figured something out.
