### ISSUE TITLE
Sourcemaps dosen't work with this plugin

### ISSUE THREAD

**Issue by TommySorensen** [dustinspecker/gulp-modify-css-urls#49]
Hi.

If this plugin is used on a stream where first we init the gulp-sourcemaps and then run gulp-sass and then gulp-modify-css-urls we end up where the lines of the sourcemaps plugin is wrong. I think that editing the urls in the css files cause the sourcemaps to point the wrong direction. Can anyone look into this, since i could not find a fix.

The main problem is that this plugin is splitting all selectors into their own line like this.
This is my css file:
```css
.classNameA, .classNameB {
     color: red;
}
```
And this is the output after the modifyCssUrls task:
```css
.classNameA,
.classNameB {
     color: red;
}
```

I am using:

```js

var sourcemaps = require('gulp-sourcemaps'),
sass = require('gulp-sass'),
modifyCssUrls = require('gulp-modify-css-urls'),
MD5 = require('md5.js'),
fs = require("fs");

gulp
	.src('somefiles')
	.pipe(sourcemaps.init())
	.pipe(sass({
		outputStyle: 'expanded',
		precision: 10
	})
	.pipe(modifyCssUrls({
		modify(url, filePath) {
			try {
				var splitUrl = url.split(/[?#]/);
				var filename = url.replace(/^.*[\\\/]/, '').replace(/[^a-zA-Z0-9]/g, '').toLowerCase();

				var stats = fs.statSync('.' + splitUrl[0]);
				return '/v-' + filename + '-' + new MD5().update(stats.size.toString()).digest('hex') + url;
			}
			catch(error) {
				return url;
			}
		}
	}))
	.pipe(sourcemaps.write('.'))
	.pipe(gulp.dest(urls.public_path));
```

**Comment by dustinspecker** [comment]
Oh, interesting. I've never added support for gulp sourcemaps.

I will try to look into this this weekend. I haven't done this before, so I can't promise when it'll be done.

If anyone wants to tackle it, it looks like we need to use https://github.com/gulp-sourcemaps/vinyl-sourcemaps-apply.

**Comment by dustinspecker** [comment]
Hey @TommySorensen,

Sorry for the delay, but I believe the latest version (1.1.0) should support sourcemaps. Would you be able to give it a try and let me know if it's working for you?

**Comment by Enkrod** [comment]
Hey @dustinspecker,

not Tommy, but just stumbled upon this on my search for a sourcemaps compatible URL-adjuster. 

The issue still exists. And I really am not doing anything special with this (for now).

```
        .pipe(modifyCssUrls({
            modify: function (url, filePath) {
                return 'Css/' + url;
            }
        }))
```

Don't have the time to look into vinyl-sourcemaps-apply right now, but when a new window for tool-development comes up I'll try to allocate some time to this if you aren't faster than me.

Thank you for your work.
