### ISSUE TITLE
Single quotes removed in data: urls

### ISSUE THREAD

**Issue by murielleholvi** [dustinspecker/gulp-modify-css-urls#55]
Hi! I'm using following setup from Yeoman's ng-poly generator:
```
.pipe($.if(isProd, $.modifyCssUrls({
    modify: function (url, filePath) {
      if (url.indexOf('data:') === 0) {
        return url;
      }

      if (url.indexOf('http') !== 0) {
        filePath = path.dirname(filePath) + path.sep;
        filePath = filePath.substring(filePath.indexOf(bowerDir) + bowerDir.length,
          filePath.length);
      }
      url = path.normalize(filePath + url);
      url = url.replace(/[/\\]/g, '/');
      return url;
    }
  })))
```

This seems to be changing `data:` urls from
```
url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 8 8'... etc.
```
to
```
url("data:image/svg+xml;charset=utf8,%3Csvg xmlns=http://www.w3.org/2000/svg viewBox=0 0 8 8... etc.
```
As you can see the single quotes are removed which breaks the SVG image.
For fun I tried using:
```
modify: function (url, filePath) {
  return url;
}
```
but even then the `data:` urls show up without single quotes, only not using `modifyCssUrls` at all seemed to fix the issue.
Any strategies on how to keep the single quotes while still using `modifyCssUrls`? :)

**Comment by dustinspecker** [comment]
Ah, good find. Looks like it's a bug over in https://github.com/reworkcss/rework-plugin-url/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc. But looks like that is no longer being maintained. I'll look into a fix in gulp-modify-css itself.

**Comment by murielleholvi** [comment]
@dustinspecker awesome :) thanks for fast reply as well

**Comment by dustinspecker** [comment]
I think it's fixed. Waiting for Travis CI and then gulp-modify-css@2.0.0 will be updated. So should just be able to upgrade to 2.0.0. I'll comment when 2.0.0 is released.

**Comment by dustinspecker** [comment]
v2.0.0 is released. Please let me know if it does not fix the issue. I probably won't be able to work on it until tonight (~10 hours away).

**Comment by murielleholvi** [comment]
@dustinspecker yes, this fixed it! Thank you 🤓 such high speed!
